#!/usr/bin/env bash
set -euo pipefail

echo "📦 1) Starting Flutter APK build..."

flutter build apk --debug --no-shrink \
  --dart-define=YOUTH_API_KEY=yAlMhwGFZps7vHtbsjnbsL6Cpha6bHqaPDSScV6pgU0 \
  --dart-define=KAKAO_MAP_API_KEY=e56be9363d2fd5a9cecd3264a29d40fc \
  --dart-define=CHAT_ENDPOINT=https://youthroad-chat-proxy.vercel.app/api/chat

# Where APK is generated by Gradle
apkSource="android/app/build/outputs/apk/debug/app-debug.apk"

if [ ! -f "$apkSource" ]; then
    echo "❌ APK was not generated: $apkSource"
    exit 1
fi

# Final APK copy location
apkTargetDir="android/build/app/outputs/flutter-apk"
apkTarget="$apkTargetDir/app-debug.apk"

echo "📂 2) Copying APK..."

mkdir -p "$apkTargetDir"
cp "$apkSource" "$apkTarget"

echo "✔ APK copy complete → $apkTarget"

echo "🚀 3) Launching Flutter with custom APK..."

flutter run --use-application-binary="$apkTarget"
