#!/usr/bin/env pwsh
Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host "📦 1) Starting Flutter APK build..."

flutter build apk --debug --no-shrink `
  --dart-define=YOUTH_API_KEY=yAlMhwGFZps7vHtbsjnbsL6Cpha6bHqaPDSScV6pgU0 `
  --dart-define=KAKAO_MAP_API_KEY=e56be9363d2fd5a9cecd3264a29d40fc `
  --dart-define=CHAT_ENDPOINT=https://youthroad-chat-proxy.vercel.app/api/chat

# APK source generated by Gradle (Flutter <3.16 uses this path)
$apkSource = "android/app/build/outputs/apk/debug/app-debug.apk"

if (-Not (Test-Path $apkSource)) {
    Write-Host "❌ APK was not generated at: $apkSource"
    exit 1
}

# Final APK copy location (Flutter uses this for run --use-application-binary)
$apkTargetDir = "build/app/outputs/flutter-apk"
$apkTarget = "$apkTargetDir/app-debug.apk"

Write-Host "📂 2) Copying APK..."

if (-Not (Test-Path $apkTargetDir)) {
    New-Item -ItemType Directory -Path $apkTargetDir | Out-Null
}

Copy-Item $apkSource $apkTarget -Force

Write-Host "✔ APK copy complete → $apkTarget"

Write-Host "🚀 3) Launching Flutter with custom APK..."

flutter run --use-application-binary="$apkTarget"
