# Gradle VM
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Kotlin metadata mismatch crash 방지
kotlin.code.style=official
kotlin.jvm.target.validation.mode=warning

kotlin.compiler.jvmTarget=17
